### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by LazarPetrovic1** [jedwards1211/import-it#4] opened 2021-04-07 14:24 UTC
No modules are imported and nothing gets logged in the console.
It simply doesn't work.
I'm stuck at **server loading 5/5 (100%)** and literally nothing happens.

**Comment by jedwards1211** [comment] 2021-04-07 14:29
This is kind of languishing since I switched to VSCode, but I've fixed various issues in the server, so let me release an update with the latest server version

**Comment by LazarPetrovic1** [comment] 2021-04-07 21:17
> This is kind of languishing since I switched to VSCode, but I've fixed various issues in the server, so let me release an update with the latest server version

Yeah I get it, happens to me too.
I should really get to fixing my own stuff.
P.S. I really love the idea of auto-imports in Atom, so I'm really looking forward to the new version

**Comment by jedwards1211** [comment] 2021-04-07 22:01
Oh you don't have to close this.  I can release a new version probably by tomorrow evening, it won't take much work

**Comment by jedwards1211** [comment] 2021-04-09 04:04
@LazarPetrovic1 okay, I just published an update, v1.1.0, do you want to see if it works?  It should fix the issue, because I experienced the server getting stuck in the past (with my VSCode extension as well) and I addressed the cause awhile back in the server package.

I also added some troubleshooting commands:
- `Import It: Open imports server log file`
- `Import It: Stop imports server gracefully`
- `Import It: Hard kill imports server`

**Comment by jedwards1211** [comment] 2021-06-02 23:33
I'm going to close this, but let me know if you have any problems after installing the updated version

**Closed as completed by jedwards1211** 2021-06-02 23:33 UTC
